-- 品番が完全一致する「ビス」の品名を、補材看板の黄色セルに合わせる。
-- 品目ID・品番・QRコードなど、品名以外は変更しない。
UPDATE items SET name = 'M5x10 AP' WHERE category = 'ビス' AND code = '+APS3TS12*253';
UPDATE items SET name = 'M3x6 ナベ' WHERE category = 'ビス' AND code = '+ﾅﾍﾞ3*6ｻﾝｶ';
UPDATE items SET name = '0' WHERE category = 'ビス' AND code = '+ﾅﾍﾞU5*10P3-3';
UPDATE items SET name = 'M4x6(P3)' WHERE category = 'ビス' AND code = '+ﾅﾍﾞM4*6P3-3';
UPDATE items SET name = 'M4x8(P3)' WHERE category = 'ビス' AND code = '+ﾅﾍﾞU4*8P3-3';
UPDATE items SET name = 'M2.6x10 P3' WHERE category = 'ビス' AND code = '+ﾅﾍﾞM2.6*10P3';
UPDATE items SET name = 'M5x10 P4' WHERE category = 'ビス' AND code = '+ﾅﾍﾞU5*10P4-3';
UPDATE items SET name = 'M4x15 P3' WHERE category = 'ビス' AND code = '+APS3TS4*15-3';
UPDATE items SET name = 'M6x12 P3' WHERE category = 'ビス' AND code = '+APS3TS6*12-3';
UPDATE items SET name = 'M３x８（黒）' WHERE category = 'ビス' AND code = 'ﾄﾗｽ3*8-3';
UPDATE items SET name = 'M3x8（サラ）' WHERE category = 'ビス' AND code = 'ｻﾗﾋﾞｽ3*8-3';
UPDATE items SET name = 'M3x15（P4）' WHERE category = 'ビス' AND code = '+ﾅﾍﾞM3*15P4-3';
UPDATE items SET name = 'M3x20（P3）' WHERE category = 'ビス' AND code = '+ﾅﾍﾞM3*20P3-3';
UPDATE items SET name = 'M4x12（P2）' WHERE category = 'ビス' AND code = '+ﾅﾍﾞM4*12P2-3';
UPDATE items SET name = 'M4x15（P3）' WHERE category = 'ビス' AND code = '+ﾅﾍﾞU4*15P3-3';
UPDATE items SET name = 'M4x25（P3）' WHERE category = 'ビス' AND code = '+ﾅﾍﾞM4*25P3-3';
UPDATE items SET name = 'M5x10（NI）トラス' WHERE category = 'ビス' AND code = 'ﾄﾗｽ5*10-N';
UPDATE items SET name = 'M５x１５（トラス）' WHERE category = 'ビス' AND code = 'ﾄﾗｽｺﾈｼﾞ5*15-3';
UPDATE items SET name = 'M5（サラ N）' WHERE category = 'ビス' AND code = 'ｻﾗﾊﾞﾈﾅｯﾄM5-3';
UPDATE items SET name = '3x10小ﾈｼﾞ(NI）' WHERE category = 'ビス' AND code = '+ﾅﾍﾞU3*10P3-C113';
UPDATE items SET name = '3x12ｻﾗ小ﾈｼﾞ(ＮI)' WHERE category = 'ビス' AND code = 'ｻﾗﾋﾞｽｺﾈｼﾞ3*12';
UPDATE items SET name = 'M3ｘ20（P4）' WHERE category = 'ビス' AND code = '+ﾅﾍﾞU3*20P4-3';
UPDATE items SET name = 'M4x25（AP）' WHERE category = 'ビス' AND code = '+APS3TS4*25-3';
UPDATE items SET name = 'Ｍ3Ｎ' WHERE category = 'ビス' AND code = 'M3Ｎ-3';
UPDATE items SET name = 'Ｍ3Ｗ(8φ)' WHERE category = 'ビス' AND code = '3*8*0.5W-3';
UPDATE items SET name = '4x10(ﾄﾗｽ)' WHERE category = 'ビス' AND code = 'ﾄﾗｽ4*10-3';
UPDATE items SET name = 'Ｍ4Ｗ(16φ)' WHERE category = 'ビス' AND code = 'M4W4*16*1.6-3';
UPDATE items SET name = '6x10ﾄﾗｽ(ＮI)' WHERE category = 'ビス' AND code = 'ﾄﾗｽ6*10-ＮI';
UPDATE items SET name = '6x12ﾄﾗｽ(ＮI)' WHERE category = 'ビス' AND code = 'ﾄﾗｽ6*12-ＮI';
UPDATE items SET name = 'Ｍ6Ｗ(13φ)' WHERE category = 'ビス' AND code = '6*13W-3';
UPDATE items SET name = '6x15ﾄﾗｽ(ＮI)' WHERE category = 'ビス' AND code = 'ﾄﾗｽ6*15-ＮI';
UPDATE items SET name = 'CAP5x10(SUS)' WHERE category = 'ビス' AND code = '6Kｱﾅﾂｷ5*10SUS';
UPDATE items SET name = 'CAP5x12(SUS)' WHERE category = 'ビス' AND code = '6Kｱﾅﾂｷ5*12SUS';
UPDATE items SET name = 'CAP6x10(SUS)' WHERE category = 'ビス' AND code = '6Kｱﾅﾂｷ6*10\SUS';
UPDATE items SET name = 'M8W(18φ）' WHERE category = 'ビス' AND code = '8*18W-3';
UPDATE items SET name = 'M8（菊座）' WHERE category = 'ビス' AND code = 'M8ｷｸｻﾞ';
UPDATE items SET name = 'M4x25(P2)' WHERE category = 'ビス' AND code = '+ﾅﾍﾞM4*25P2-3';
